### ISSUE TITLE
Release checklist 7/30/14

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-editor#29]
#### Priorities
- [x] Automated tile generation (TileLive)

#### Supported features for next release
- [x] Points of Interest
- [x] Buildings

#### Data
- [x] Finalize building schema (work with Brian and Darcee)
- [x] Create JSON files for building schema (work with Mamata)

#### Publishing to dos
- [x] Export to FGDB nightly
- [ ] Metadata record in the data store that points to FGDB snapshots (work with David Warren)

#### Before Release
- [x] Testing

#### Communication
- [x] Sit down with David to figure out communication strategy with the GIS community
- [x] Places Mapping Party

#### Backlog
- [ ] ChangeWithin

**Comment by nateirwin** [comment]
Once @jimmyrocks gets back into the office, let’s sit down and talk about this release and develop another checklist like this.

**Comment by nateirwin** [comment]
Closing because most of these tasks have been completed and/or have their own issues at this point.
